d=int(input("enter the days"))
y=int(d/365)
print("the total number of year",y)
a=int(d%365)
m=int(a/30)
print("the total number of month",m)
b=int(a%30)
w=int(b/7)
print("the total number of week",w)
dd=int(b%7)
print("the number of days",dd)