a=int(input("enter a value"))
b=int(input("enter b value"))
print("area",a*b/2)
print("add=",a+b)
print("sub=",a-b)
print("mul=",a*b)
print("div=",a/b)
print("mod=",a%b)
print("expo=",a**b)
print("floor div=",a//b)