m1=int(input("enter the marks of m1"))
print("the marks of m1",m1)
m2=int(input("enter the marks of m2"))
print("the marks of m1",m2)
dsu=int(input("enter the marks of dsu"))
print("the marks of m1",dsu)
java=int(input("enter the marks of java"))
print("the marks of m1",java)
oop=int(input("enter the marks of oop"))
print("the marks of m1",oop)
total=(m1+m2+dsu+java+oop)
print("the total marks of 500",total)
per=((total/500)*100)
print("percentage =>>",per)