str=" sakshi malwadkar "
print(len(str))
print(str.lower())
print(str.upper())
print(str.capitalize())
print(str.title())
print(str.strip())
print(str.replace('sakshi','hello'))
print(str.split(','))
print(str.join('str'))
print(str.find('m'))
print(str.count('i'))
print(str.startswith('sakshi'))
print(str.endswith("world"))
